# Contributor: Ryan Wiseman <ryanwisemanmusic@gmail.com>
# Maintainer: Ryan Wiseman <ryanwisemanmusic@gmail.com>
pkgname=juce
pkgver=7.0.8
pkgrel=1
pkgdesc="Headless JUCE framework for audio applications"
url="https://juce.com/"
arch="x86_64"
license="GPL-3.0-or-later"
depends="
alsa-lib
curl
freetype
gcompat
gtk+3.0
libdw
"
makedepends="
alsa-lib-dev
cmake
curl-dev
freetype-dev
gtk+3.0-dev
libx11-dev
libxcomposite-dev
libxcursor-dev
libxext-dev
libxinerama-dev
libxrandr-dev
mesa-dev
musl-dev
samurai
"
options="!check"
subpackages="$pkgname-doc $pkgname-examples $pkgname-extras"
source="juce-$pkgver.tar.gz::https://github.com/juce-framework/JUCE/archive/refs/tags/$pkgver.tar.gz
	cmake.sh
    execinfo-compat.sh
	locale_compat.sh
	locale_python_script.sh
    juce_bineof.sh
	juce_config.sh
    juce_cmake_eof.sh
    juce_pc_eof.sh
	"
builddir="$srcdir/JUCE-$pkgver"
sha512sums="
271f241cfb76bc1ea1838d9ba552b893d1d8df413d24b051ffb31c6c9b7eff10d18c16d3e8b03c9a910470508e2177aa2d15eab208974171d5835b8b62fcabdf  juce-$pkgver.tar.gz
9107951808c2125ca4e2aa0852707435f1d133acbf35e43d59f50a24987d043acb7705a65ac1a5d0a5ee013fe1340519630d0af2bd49c3486db76fd19deacf20  cmake.sh
fa51e31afe89f338165aa4dc7e60f0786d62503c3b7df1c6ee82d0fba1599dc7df68d879782b8aa949cd05b418a85431f5dcacb8549e991eb584a8841e978d11  execinfo-compat.sh
8dfc8f0bd80634148a92112404f6370f83a1483cdc0289262d7497ca3519214eb8b00bd949952dc9560ecc48752149ea10c59fae9ab0cb80fb18b4c83a656207  locale_compat.sh
56219c286b1d6ef89522f3760a66012ee6e8327a5b7609775801fae32ecba40ef99a4390d4521b38edc6d4482c303567ad87ffac75d785c6f2e46368b5086cf2  locale_python_script.sh
ca401d6ba322850051adb996431512900bea50a7aa012ed439a3f70a567c5c0ce6455028d0512e8b2e8de3f191dd8f552c6dda9e60722783a4510e7d11674dbb  juce_bineof.sh
b6a85d6485b40dc9a52960f1053b1d2b463a8af01e0360d9f94adac76f00dfe96080300abed68438a0acacb85de3ea674bdc1a8f59114ae844cea603959269c6  juce_config.sh
e7cf5307103d8fddc1abe91ae95ad90edfda55d658583155019c73927244b6cef08d8a858b6ce346b8af2eacc5f17563dee3cc008b47964c94d69e2fb596d7cd  juce_cmake_eof.sh
b54a85d2d3b1ab468a79df2876fc9bc4b5b2055be039d7bc5182e45069c5fb9dea02e3f7303717a865c99f651f4c551f209fb4cc4a26a5cc57cf8ee8fdcea9a8  juce_pc_eof.sh
"
prepare() {
    default_prepare
    if [ ! -d "$builddir/modules" ]; then
        error "modules directory missing in $builddir"
        return 1
    fi
    echo "=== Disabling optional components that require missing dependencies ==="
	# As a note, we do have to disable the web browser component and sometimes curl. The web component also needs to be stripped from the autogenerated CMake file JUCE has. 
	# I wish this wasn't the case, so if anyone can figure out a way to fix this problem, feel free to pull request this with a fix
    find "$builddir/modules" -type f \( -name "*.h" -o -name "*.cpp" -o -name "*.cmake" -o -name "CMakeLists.txt" \) -exec \
        sed -i 's/JUCE_WEB_BROWSER 1/JUCE_WEB_BROWSER 0/g' {} \;
    find "$builddir/modules" -type f \( -name "*.h" -o -name "*.cpp" -o -name "*.cmake" -o -name "CMakeLists.txt" \) -exec \
        sed -i 's/JUCE_USE_CURL 1/JUCE_USE_CURL 0/g' {} \;
    find "$builddir/modules" -name "*.cmake" -type f -exec \
        sed -i 's/webkit2gtk-4\.0//g' {} \;
    find "$builddir/modules" -name "CMakeLists.txt" -type f -exec \
        sed -i 's/webkit2gtk-4\.0//g' {} \;
    find "$builddir/modules" -name "*.cmake" -type f -exec \
        sed -i '/webkit2gtk/d' {} \;
    # I use shell scripts as a mean of doing anything related to creating new files
    . "$srcdir/execinfo-compat.sh"
    . "$srcdir/locale_compat.sh"
    create_locale_compat_header "$builddir"
    . "$srcdir/locale_python_script.sh"
    . "$srcdir/juce_config.sh"
    create_juce_config_header "$builddir"
    # This will handle the issue related to errno.h
    find "$builddir/modules" -type f \( -name "*.cpp" -o -name "*.h" \) -exec \
        sed -i 's|#include <sys/errno.h>|#include <errno.h>|g' {} \;
    local stats_file="$builddir/modules/juce_core/native/juce_SystemStats_linux.cpp"
    sed -i '1i #include "locale_compat.h"' "$stats_file"
    # Fix stat64 for musl
    sed -i 's/struct stat64/struct stat/g' \
        "$builddir/modules/juce_core/native/juce_SharedCode_posix.h"
    sed -i 's/stat64/stat/g' \
        "$builddir/modules/juce_core/native/juce_SharedCode_posix.h"
    # Then, you can finally patch the locale functions
    patch_locale_functions "$stats_file"
    sed -i '1i #include <tuple>' "$builddir/modules/juce_core/containers/juce_FixedSizeFunction_test.cpp"
}

build() {
    cd "$builddir"
    echo "=== Building JUCE modules using unity build pattern ==="
    # Handle CMake configuration
    . "$srcdir/cmake.sh"
    create_cmake_file "$builddir"
    cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_CXX_FLAGS="-fPIC -DNDEBUG" 2>&1 | grep -v "WARNING: juce-examples\*: No arch specific binaries found" | grep -v "WARNING: juce-extras\*: No arch specific binaries found" | grep -v "WARNING: juce-examples\*: Split function set arch=" | grep -v "WARNING: juce-extras\*: Split function set arch="
    echo "=== Starting compilation (this may take several minutes) ==="
    cmake --build build --parallel "$(nproc)" 2>&1 | grep -v "WARNING:.*No arch specific binaries found" || {
        echo "=== Build failed, showing last 50 lines of error ==="
        tail -50 "$builddir/build/CMakeFiles/CMakeError.log" 2>/dev/null || true
        return 1
    }
    echo "=== Verifying built libraries ==="
    find "$builddir/build" -name "*.a" -exec ls -lh {} \;
}

package() {
    cd "$builddir"
    echo "=== Installing JUCE static libraries ==="
    # There is a bunch of CMake related code we handle through the our various .sh files.
    DESTDIR="$pkgdir" cmake --install build
    echo "=== Verifying installed libraries ==="
    find "$pkgdir/usr/lib" -name "libjuce*.a" -exec ls -lh {} \;
    . "$srcdir/juce_pc_eof.sh"
    create_pkg_config "$pkgdir" "$pkgver"
    . "$srcdir/juce_cmake_eof.sh"
    create_cmake_config "$pkgdir" "$pkgver"
    . "$srcdir/juce_bineof.sh"
    create_juce_config_binary "$pkgdir"
}

doc() {
    pkgdesc="$pkgdesc (documentation)"
    mkdir -p "$subpkgdir/usr/share/doc/$pkgname"
}

examples() {
    pkgdesc="$pkgdesc (example code)"
    if [ -d "$builddir/examples" ]; then
        mkdir -p "$subpkgdir/usr/share/$pkgname"
        cp -r "$builddir/examples" "$subpkgdir/usr/share/$pkgname/examples"
    fi
}

extras() {
    pkgdesc="$pkgdesc (additional utilities)"
    if [ -d "$builddir/extras" ]; then
        mkdir -p "$subpkgdir/usr/share/$pkgname"
        cp -r "$builddir/extras" "$subpkgdir/usr/share/$pkgname/extras"
    fi
}
# Add subpackages related to docs, examples, and extras
subpackages="$pkgname-doc $pkgname-examples $pkgname-extras"

# Note: webkit2gtk-4.0 is not included. It would not upgrade to 4.1, therefore, I've disabled it via grep
# Language modules have been disabled for now, due to their inability to be incorporated into Alpine properly.
# While each module has supposedly been added to this APKBUILD file (from what I can tell), I cannot ensure that every tiny little thing works.
# When you invoke stuff explicitly from the library, and not just headers-only stuff, you successfully can call without things being undefined.
# This will receive additional updates if there's bugs. JUCE is a massive framework, and therefore, it requires more code than 90% of Alpine packages.
# Note: I'll upgrade this to V8 at some point, I was just worried that V8 would have some even stricter standards

# The only thing missing is: audio_plugin_client. Weird, I'll try to test this out later